import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { AppBar } from "@/components/AppBar/AppBar";
import Swapi from "./swapi";
import {
  SpreedlyTokenisationComponent,
  TokenisationCompomentResponse,
} from "@utilitywarehouse/spreedly-tokenisation-component";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AppBar title={"App Bar"} />
        <Swapi />
        <SpreedlyTokenisationComponent
          spreedlyEnv="prod"
          onReturnSpreedlyResponse={(data) => console.log("THIS IS IT: ", data)}
        />
        <div>
          <p>Index</p>
        </div>
      </main>
    </>
  );
}
